language: node_js
node_js:
  - 0.12
before_script:
  - "npm install -g mocha"
  - "cp .env.sample .env"
script:
  - "mocha -R spec spec.js"
before_deploy:
  - echo -e "Host csh-cloud.oweb.co\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  # - provider: script
  #   script: .travis/deploy_stage.sh
  #   on:
  #     branch: develop
  #     repo: Herrd/herrd-push-server
  - provider: script
    script: .travis/deploy_prod.sh
    on:
      branch: master
      repo: Herrd/herrd-push-server
